# Generated by Django 4.2.16 on 2024-11-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_stockdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdetails',
            table='StockDetails',
        ),
    ]
